name: Create Zip for Delivery 

on:
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set ZIP_NAME with current date
        run: echo "ZIP_NAME=DMAV_ilivalidator_$(date +'%Y-%m-%d').zip" >> $GITHUB_ENV

      - name: Create zip file
        run: zip "$ZIP_NAME" -r ilivalidator -r ilimodels\validation_models config\DMAV_V1_0_Validierung_Alle_Modelle.ini

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Delivery
          path: Delivery/${{ env.ZIP_NAME }}

